language: node_js
node_js:
  - '6'
env:
  - CXX=g++-4.8
addons:
  postgresql: "9.4"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - psql -U postgres -c 'create database levelplayingfield;'
script:
  - npm run lint
    #  - npm run test
